// <auto-generated />
using System;
using ComicViewer.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicViewer.Web.Migrations
{
    [DbContext(typeof(ComicBookContext))]
    [Migration("20190226012203_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("ComicViewer.Core.ComicBookFile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Extension");

                    b.Property<int>("Height");

                    b.Property<string>("Issue");

                    b.Property<int>("Length");

                    b.Property<string>("Month");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalName");

                    b.Property<string>("Path");

                    b.Property<string>("Publisher");

                    b.Property<byte[]>("Thumbnail");

                    b.Property<string>("Title");

                    b.Property<string>("Volume");

                    b.Property<int>("Width");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
