// <auto-generated />
using System;
using ComicViewer.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicViewer.Web.Migrations
{
    [DbContext(typeof(ComicBookContext))]
    partial class ComicBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("ComicViewer.Core.ComicBookListing", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Height");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfPages");

                    b.Property<string>("Path");

                    b.Property<byte[]>("Thumbnail");

                    b.Property<DateTime>("Updated");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("Listing");
                });
#pragma warning restore 612, 618
        }
    }
}
